# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SOL's note
email: sk618dev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  s01k1m



# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: s01k1m/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - _pages


footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/s01k1m"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      # url: "https://www.linkedin.com/in/renatogolia/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/Kralizek"
    # - label: "Stack Overflow"
    #   icon: "fab fa-fw fa-stack-overflow"
    #   url: "https://stackoverflow.com/users/82540"


author:
  name   : "SK"
  avatar : "/assets/images/ìŠ¤ë…¸ìš°ë³¼.gif"
  bio    : >-
    
    ğŸ¤”ì¼ë‹¨ 5ë¶„ë§Œ ë” í•˜ìğŸ¤” <br>
    ğŸ•ºì½”ë”© + ìŒì•… = so gooood!ğŸ•º
  # You can read more about me in the [About me](/about/) section.
  location: "Seoul"
  # twitter: "Kralizek"
  # linkedin: "renatogolia"
  github: "s01k1m"
  # stackoverflow: "82540"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:sk618dev@gmail.com"
    # - label: "Resume"
    #   icon: "far fa-fw fa-file-pdf"
    #   url: "/assets/files/resume-renato-golia.pdf"


repository: s01k1m/s01k1m.github.io

github: [metadata]


# customize css
sass:
  sass_dir: _sass
